# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'DoubleSpeak Magazine'
description:      'a journal for poetry in translation'
url:              'https://makeademic.github.io'
baseurl:          '/my-wax-site'
copyright:        'Copyright 2017-2025'
logo:             '/assets/logo.png'
default_thumb:    '/assets/default.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:

  #used to generate the tags for the site
  author_tags:
    layout: 'tagpage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'authors.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  language_tags:
    layout: 'tagpage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'languages.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  translator_tags:
    layout: 'tagpage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'translators.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  poems_2024:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2024.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2024:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2024.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'


  poems_2023:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2023.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2023:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2023.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'


  #used to generate the poem + note pages for each issue/year
  poems_2022:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2022.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2022:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2022.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  poems_2021:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2021.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2021:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2021.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  poems_2020:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2020.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2020:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2020.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  poems_2019:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2019.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2019:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2019.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  poems_2018:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2018.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2018:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2018.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  poems_2017:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2017.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2017:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2017.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

  poems_2016:
    layout: 'poempage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2016.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'
  notes_2016:
    layout: 'notepage'
    output: true # this must be true for your .md pages to be built to html!
    metadata:
      source: 'poems_2016.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'source_images/objects' # path to the directory of source images, must be within '_data'

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      poems_2024:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2023:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2022:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2021:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2020:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2019:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2018:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2017:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
      poems_2016:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - transtitle
          - title
          - author
          - translator
          - poem
          - transpoem
          - language
# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    link: '/about/'
  - label: 'issues'
    link: '/issues/'
  - label: 'Search'
    link: '/search/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/minicomp/wax'
    - label: 'Credits'
      link: '/credits'
    - label: 'Wiki'
      link: 'https://minicomp.github.io/wiki/wax/'
  logos:
    - img: '/img/logo.png'

# FIN
